all:
	gcc -c funcoes_auxiliares.c
	gcc -c vetor_aleatorio.c
	gcc -c selection_min_k.c
	gcc -c heap_min_k.c
	gcc -c quick_min_k.c
	gcc -c main.c
	gcc funcoes_auxiliares.o vetor_aleatorio.o selection_min_k.o heap_min_k.o quick_min_k.o main.o -o main
	