all:
	gcc -g -c funcoes_auxiliares/funcoes_auxiliares.c
	gcc -g -c abb/abb.c
	gcc -g -c sorting/abb_sort.c
	gcc -g -c arn/arn.c
	gcc -g -c sorting/arn_sort.c
	gcc -g -c avl/avl.c
	gcc -g -c sorting/avl_sort.c
	gcc -g -c main.c
	gcc funcoes_auxiliares.o abb.o abb_sort.o arn.o arn_sort.o avl.o avl_sort.o main.o -o main
